import type { Metadata } from "next";

import "./globals.css";
import Responsivenav from "./components/navbar/responsivenav";
import Footer from "./components/footer/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
      <Responsivenav />
      <div className="">

        {children}
      </div>
        <Footer/>
      </body>
    </html>
  );
}
