import type { Metadata } from "next";

import "./globals.css";
import Responsivenav from "./components/navbar/responsivenav";
import Footer from "./components/footer/footer";
import Scrolltotop from "./components/helper/helper";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
     
      <div className="">
           
        {children}
        <Scrolltotop/>
      </div>
      
       
      </body>
    </html>
  );
}
